name: Dispatch SMS
on:
  workflow_dispatch:
    inputs:
      number:
        default: "+1(346)2049381"
        type: string
      message:
        default: "Hello World!"
        type: string

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-queue@v1
      - name: "Sending SMS Notification"
        run: echo "Hello World!!!"
      - name: "Test"
        run: sleep 60
