name: Dispatch SMS
on:
  workflow_dispatch:
    inputs:
      number:
        default: "+1(346)2049381"
        type: string
      message:
        default: "Congratulations Privateer! \n As a student of the University of New Orleans, you have been nominated for the position of “King of Fucking Bitches and Getting Money”. An election will commence on March 12, 2023 where you will run against seven other men, one of whom has a Cinnamon addiction, for this coveted title. \n We wish you the best of luck in this endeavor. \n Reply “STOP” to discontinue future messages."
        type: string

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Sending SMS Notification"
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: "+1(314)8873826"
          toPhoneNumber: "${{ inputs.number }} "
          message: ${{ inputs.message }}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
