name: hello-world
on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          sleep 30
          echo "Hello World!"
          
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          sleep 30
          echo "Hello World!"
  my-job3:
    needs: my-job2
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          sleep 30
          echo "Hello World!"
  
  my-job4:
    needs: [my-job2, my-job3]
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          sleep 30
          echo "Hello World!"

  my-job5:
    runs-on: ubuntu-latest
    needs: [my-job3]
    steps:
      - name: my-step
        run: |
          sleep 30
          echo "Hello World!"
    
  dispatch_workflow:
    needs: [my-job3, my-job4]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: hello-world
          token: ${{ secrets.PERSONAL_TOKEN }}
